---
title: "Impact of COVID-19, Economies"
author: "Jun-Yong Kim"
date: "4/1/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(dplyr)
library(rvest)
library(gt)
library(janitor)
library(infer)
library(skimr)
library(tidycensus)
library(maps)
library(sf)
library(tibble)
library(stringr)
library(readxl)
```

```{r scraping, include = FALSE}

worldometer_url <- paste0("https://www.worldometers.info/coronavirus/")
worldometer_html <- read_html(worldometer_url)

worldometer <- worldometer_html %>% 
               html_nodes("table")
worldometer <- worldometer[[1]] %>% html_table
worldometer <- worldometer %>% clean_names()


```


```{r pop_gdp_data, include = FALSE}

population_data_18 <- read_csv("data_misc/API_pop.csv", skip = 3) %>% 
  clean_names() %>% 
  select(country_name, x2018) %>% 
  rename(pop_2018 = x2018)
  
gdp_data_18 <- read_csv("data_misc/API_gdp.csv", skip = 3) %>%
  clean_names() %>% 
  select(country_name, x2018) %>% 
  rename(gdp_2018 = x2018)

gdp_pop_2018 <- gdp_data_18 %>% 
  left_join(population_data_18, by = "country_name") %>% 
  mutate(gdp_per_capita = round(gdp_2018 / pop_2018, digits = 2))

```

```{r econ_indicators, include = FALSE}

indices_url <- paste0("https://markets.businessinsider.com/indices")
indices_html <- read_html(indices_url)

indices <- indices_html %>% 
               html_nodes("table")

indices <- indices[[2]] %>% 
  html_table

indices <- indices %>% 
  clean_names()

misc_data <- read_excel("data_misc/msci0406.xls", skip = 5) %>% 
  clean_names()

nasdaq <- read_csv("data_misc/nasdaq0406.csv") %>% 
  clean_names()
  

#jhu_us_confirmed_series <- read.csv(
#  "jhu_covid_data/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv"
#  ) %>% 
 # clean_names()


```

```{r combining, include= FALSE}

#tidy_jhu_us_confirmed <- jhu_us_confirmed_series %>%
#  pivot_longer(cols = c(x1_22_20:x4_2_20), names_to = "date", values_to = "confirmed") %>%
#  select(country_region, fips, combined_key, date, confirmed)

#tidy_jhu_us_confirmed %>%
 # group_by(combined_key, date) %>%
 # arrange(desc(confirmed))


tidy_gdp_pop <- gdp_pop_2018 %>% 
  left_join(worldometer, by = c("country_name" = "country_other")) %>% 
  select(country_name, pop_2018, gdp_2018, gdp_per_capita, total_cases, total_deaths, total_recovered) %>% 
  na.omit()
```

```{r plots, echo = FALSE}

cases_gdp_capita <- tidy_gdp_pop %>% 
  ggplot(aes(x = total_cases, y = gdp_per_capita)) + 
  geom_point()

# plot is coming out really whack. 

deaths_gdp_capita <- tidy_gdp_pop %>% 
  ggplot(aes(x = total_deaths, y = gdp_per_capita)) + 
  geom_point()
```


How can I match daily / weekly / monthly data with each other when they're not the same? 


