
---
title: "Healthcare Capacity"
author: "Katelyn Li"
date: "4/1/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(ggplot2)
library(infer)

```

```{r read data}

hospital_beds <- read.csv("hospital-beds-per-1000-people.csv")

physicians_per_1000 <- read.csv("physicians-per-1000-people.csv")

```

```{r}


hospital_beds %>%
  filter(Year == 2015) %>%
  ggplot(mapping = aes(x = reorder(Entity, Hospital.beds..per.100.000.), y = Hospital.beds..per.100.000.)) +
  geom_col() +
  theme_classic() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(x= "Country", 
       y = "Hospital Beds Per 100000 People")



```


```{r}

physicians_per_1000 %>%
  filter(Year == 2015) %>%
  ggplot(mapping = aes(x = reorder(Entity, Physicians..per.1.000.people...per.1.000.people.), y = Physicians..per.1.000.people...per.1.000.people.)) +
  geom_col() +
  theme_classic() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(x= "Country", 
       y = "Physicians Per 1000 People")

```

```{r}

left_join()