---
title: "spread_final"
author: "Nishu Lahoti"
date: "4/16/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(dplyr)
library(readr)
library(rvest)
library(janitor)
library(skimr)
# library(sf)
# library(maps)
# library(tibble)
library(stringr)
library(tibble)
library(plotly)
library(infer)

# Import NYTimes Data

us_states <- read.csv(url("https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv"))
us_counties <- read.csv(url("https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv"))

saveRDS(us_states, file = "../team_data/nytimes_states.RDS")
saveRDS(us_counties, file = "../team_data/nytimes_counties.RDS")


# Import & Clean Johns Hopkins Data

us_confirmed <- read.csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv")) %>% 
  clean_names() %>%
  pivot_longer(cols = c(x1_22_20:x5_4_20), names_to = "date", values_to = "confirmed") %>%
  select(combined_key, date, confirmed)

us_deaths <- read.csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_US.csv")) %>% 
  clean_names() %>%
  pivot_longer(cols = c(x1_22_20:x5_4_20), names_to = "date", values_to = "deaths") %>%
  select(combined_key, date, deaths)

global_confirmed <- read.csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv")) %>% 
  clean_names() %>%
  pivot_longer(cols = c(x1_22_20:x5_4_20), names_to = "date", values_to = "confirmed") %>%
  select(country_region, date, confirmed)

global_deaths <- read.csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv")) %>% 
  clean_names() %>%
  pivot_longer(cols = c(x1_22_20:x5_4_20), names_to = "date", values_to = "deaths") %>%
  select(country_region, date, deaths)

global_recovered <- read.csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv")) %>% 
  clean_names() %>%
  pivot_longer(cols = c(x1_22_20:x5_4_20), names_to = "date", values_to = "recovered") %>%
  select(country_region, date, recovered)

# global_recovered_2 <- read.csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv")) %>%
#   clean_names() %>%
#   pivot_longer(cols = -c(province_state, country_region, lat, long), names_to = "date",
#                values_to = "confirmed")

us_daily_reports <- read.csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports_us/04-17-2020.csv")) %>% clean_names()


# Webscrape Worldometer Data

worldometer_url <- paste0("https://www.worldometers.info/coronavirus/")
h <- read_html(worldometer_url)
table <- h %>% html_nodes("table")
worldometer <- table[[1]] %>% html_table


world <- worldometer %>% 
  clean_names() %>%
  mutate_at(c("total_cases", "total_deaths", "total_recovered", "total_tests", "tests_1m_pop"), parse_number) %>%
  filter(! country_other %in% c("World", "Total:", "Europe", "North America", "Asia", "South America", 
                                "Africa", "Oceania", "")) %>%
  mutate(incidence = case_when(
    total_cases > 100000 ~ "100,000+ Cases",
    total_cases >= 10000 ~ "10,000+ Cases",
    total_cases >= 1000 ~ "1,000+ Cases",
    TRUE ~ "Less than 1000+ Cases"
  ),
  population_estimate = (total_tests * 1000000) / tests_1m_pop,
         per_capita_cases = total_cases / population_estimate,
         per_capita_tests = total_tests / population_estimate) %>%
  select("country_other", "population_estimate", "total_cases", "total_deaths", "total_recovered", "total_tests", "tests_1m_pop", incidence) %>%
  arrange(desc(total_cases))

saveRDS(world, file = "../covid19_data_gov1005/worldometer.RDS")

```

### Creating increments

```{r increments, echo = FALSE}

# Updating the date and creating an increment column for the confirmed cases in the US.

confirmedCovidUS <- us_confirmed %>%
  mutate(sep_date = sub(".", "", date)) %>%
  mutate(new_date = as.Date(sep_date, format = "%m_%d_%y")) %>%
  select(combined_key, new_date, confirmed)

confirmedCovidUS <- confirmedCovidUS %>%
  mutate(helper = c(confirmedCovidUS$confirmed[1], confirmedCovidUS$confirmed[1:(nrow(confirmedCovidUS)-1)])) %>%
  mutate(increment = confirmed - helper) %>%
  group_by(combined_key)

# Updating the date and creating an increment column for the confirmed cases in the US.

deathsCovidUS <- us_deaths %>%
  mutate(sep_date = sub(".", "", date)) %>%
  mutate(new_date = as.Date(sep_date, format = "%m_%d_%y")) %>%
  select(combined_key, new_date, deaths)

deathsCovidUS <- deathsCovidUS %>%
  mutate(helper = c(deathsCovidUS$deaths[1], deathsCovidUS$deaths[1:(nrow(deathsCovidUS)-1)])) %>%
  mutate(increment = deaths - helper) %>%
  group_by(combined_key)

# Updating the date and creating an increment column for the confirmed cases across the globe

confirmedCovidGlobal <- global_confirmed %>%
  mutate(sep_date = sub(".", "", date)) %>%
  mutate(new_date = as.Date(sep_date, format = "%m_%d_%y")) %>%
  select(country_region, new_date, confirmed)

confirmedCovidGlobal <- confirmedCovidGlobal %>%
  mutate(helper = c(confirmedCovidGlobal$confirmed[1],
                    confirmedCovidGlobal$confirmed[1:(nrow(confirmedCovidGlobal)-1)])) %>%
  mutate(increment = confirmed - helper) %>%
  group_by(country_region)

# Updating the date and creating an increment column for the deaths  across the globe

deathsCovidGlobal <- global_deaths %>%
  mutate(sep_date = sub(".", "", date)) %>%
  mutate(new_date = as.Date(sep_date, format = "%m_%d_%y")) %>%
  select(country_region, new_date, deaths)

deathsCovidGlobal <- deathsCovidGlobal %>%
  mutate(helper = c(deathsCovidGlobal$deaths[1],
                    deathsCovidGlobal$deaths[1:(nrow(deathsCovidGlobal)-1)])) %>%
  mutate(increment = deaths - helper) %>%
  group_by(country_region)

# Updating the date and creating an increment column for the recovered cases across the globe

recoveredCovidGlobal <- global_recovered %>%
  mutate(sep_date = sub(".", "", date)) %>%
  mutate(new_date = as.Date(sep_date, format = "%m_%d_%y")) %>%
  select(country_region, new_date, recovered)

recoveredCovidGlobal <- recoveredCovidGlobal %>%
  mutate(helper = c(recoveredCovidGlobal$recovered[1],
                    recoveredCovidGlobal$recovered[1:(nrow(recoveredCovidGlobal)-1)])) %>%
  mutate(increment = recovered - helper) %>%
  group_by(country_region)

# Joined Data US & Global

covidUS <- confirmedCovidUS %>%
  inner_join(deathsCovidUS, by = c("combined_key", "new_date"), suffix = c("_confirmed", "_deaths")) %>%
  select(combined_key, new_date, confirmed, increment_confirmed, deaths, increment_deaths)

covidGlobal <- confirmedCovidGlobal %>%
  inner_join(deathsCovidGlobal, by = c("country_region", "new_date"), suffix = c("_confirmed", "_deaths")) %>%
  inner_join(recoveredCovidGlobal, by = c("country_region", "new_date"), suffix = c("_confirmed", "_recovered")) %>%
  inner_join(country_population, by = c("country_region" = "Country")) %>%
  mutate(
    cases_per_capita = confirmed / pop_2018,
    deaths_per_capita = deaths / pop_2018
  ) %>%
  select(country_region, pop_2018, new_date, confirmed, increment_confirmed, deaths, increment_deaths, recovered, increment, cases_per_capita, deaths_per_capita)

# Johns Hopkins US Daily Report. Used to gather testing rates by State.

testing_by_state <- us_daily_reports %>%
  filter(!is.na(people_tested))

# Saving files for team use

saveRDS(covidUS, file = "../team_data/covidUS.RDS")
saveRDS(covidGlobal, file = "../team_data/covidGlobal.RDS")
saveRDS(testing_by_state, file = "../team_data/tests_per_state.RDS")
```

## Exploratory Data Analysis

```{r exploration, echo = FALSE}

worldometer %>%
  skim()

summary(covidUS)
summary(covidGlobal)

```

### Global Exploration

#### Johns Hopkins Data
```{r exploring_global_visuals, echo = FALSE}

# Creating a visualization of the spread across different countries by mapping new_date against increment confirmed and deaths. Could create this as a drop-down selector for any country's confirmed and deaths. Maybe even compare side-by-side.

# Confirmed

countries_of_interest <- covidGlobal %>%
  filter(country_region %in% c("US", "Spain", "Italy"), increment_confirmed >= 0)

ggplot(countries_of_interest, aes(new_date, increment_confirmed)) + 
  geom_col() +
  facet_wrap(~ country_region) +
  theme_classic()

country <- covidGlobal %>%
  filter(country_region == "Afghanistan", confirmed > 0, increment_confirmed >= 0) %>%
  arrange(desc(new_date))

country_regression <- lm(confirmed ~ new_date, data = country) %>%
  tidy(conf.int = TRUE)

slope_overall = (max(country$confirmed) - min(country$confirmed)) / nrow(country)
slope_seven = country$confirmed[1] - country$confirmed[7] / 7

ggplot(country, aes(new_date, increment_confirmed)) +
  geom_col(fill = "#E64A19") +
  geom_smooth(se = FALSE, color = "black") +
  theme_classic()

# Deaths

countries_of_interest <- covidGlobal %>%
  filter(country_region %in% c("US", "Spain", "Italy"), increment_deaths >= 0)

ggplot(countries_of_interest, aes(new_date, increment_deaths)) + 
  geom_col() +
  facet_wrap(~ country_region) +
  theme_classic() +
  labs(
    title = "Visualizing Spread in Western Europe"
  )


us_data <- covidGlobal %>%
        filter(country_region == "US", 
               increment_confirmed >= 0,
               increment_deaths >= 0,
               increment >= 0)
  
 
# Will come back to this...

     # ggplot(us_data, aes(x = new_date)) +
     #    geom_histogram(data = us_data$increment_confirmed, fill = "blue", alpha = 0.2) +
     #    geom_histogram(data = us_data$increment_deaths, fill = "red", alpha = 0.2) +
     #    geom_histogram(data = us_data$increment, fill = "green", alpha = 0.2)


```

#### Worldometer Data
```{r worldometer_exploration, echo = FALSE}
# Visualizing total cases and total deaths against total tests. A good next step may be to filter by countries of interest and to get a good enough
# sample of countries that have tested. Qualify a country based on total number of cases (>1000). Maybe there is a weak positive correlation.

options(scipen = 999)

# Normal
worldometer_tests <- world %>%
  filter(total_cases >= 15000, 
         !is.na(total_tests))

# Logarithmic

worldometer_log <- world %>%
  mutate(log_cases = log(total_cases),
         log_deaths = log(total_deaths),
         log_recovered = log(total_recovered),
         log_tests = log(total_tests),
         log_tests_1m = log(tests_1m_pop))

ggplot(worldometer_tests, aes(total_tests, total_cases, color = country_other)) + 
  geom_point() +
  geom_jitter() +
  theme_classic() +
  theme(legend.position = "right") +
  labs(
    title = "Comparing COVID-19 Cases versus Total Tests",
    subtitle = "Comparing total conducted tests \nfor countries with over 15,000 reported cases.",
    x = "Total Tests",
    y = "Total Cases",
    color = "Country"
  )

ggplot(worldometer_tests, aes(tests_1m_pop, total_cases, color = country_other)) + 
  geom_point() +
  geom_jitter() +
  theme_classic() +
  theme(legend.position = "right") +
  labs(
    title = "COVID-19 Country Testing Capacity",
    subtitle = "Visualizing a country's case rate against testing rate\nfor countries with over 15,000 reported cases.",
    x = "Tests per 1M",
    y = "Cases",
    color = "Country"
  )

# Logarithmic plot of total tests

log_test_plot <- ggplot(worldometer_log, aes(log_tests, log_cases, color = country_other)) +
  geom_point() +
  theme(legend.position = "none") +
  labs(
    title = "Logarithmic comparison of tests to cases",
    x = "Tests \n(x10,000)",
    y = "Cases \n(x10,000)",
    caption = "Disclaimer about logarithmic tests"
  )

log_test_ply <- ggplotly(log_test_plot)
log_test_ply

# Logarithmic plot of tests per 1m

log_1m_plot <- ggplot(worldometer_log, aes(log_tests_1m, log_cases, color = country_other)) +
  geom_point() +
  theme(legend.position = "none") +
  labs(
    title = "Logarithmic comparison of cases to tests",
    x = "Tests per 1M \n(x10,000)",
    y = "Cases \n(x10,000)",
    caption = "Disclaimer about logarithmic tests"
  )

log_1m_ply <- ggplotly(log_1m_plot)
log_1m_ply

```

### US Exploration
#### Johns Hopkins Data
```{r exploration_visualizing_US, echo = FALSE}

# Visualizing total tests per state using Johns Hopkins data.

# This function capitalizes the first letter of a string. Necessary because the data from the maps library
# which is used to collect geometry information from states needs to be augmented such that it can be joined.

CapStr <- function(y) {
  c <- strsplit(y, " ")[[1]]
  paste(toupper(substring(c, 1,1)), substring(c, 2),
      sep="", collapse=" ")
}

# Using a mix of the sf, tibble, and maps library to pull the geometry data by state into a table 
# which we can join on the Johns Hopkins data.

us <- st_as_sf(map("state", plot = FALSE, fill = TRUE))
us_tbl <- as_tibble(us) %>%
  mutate(state_chr = as.character(ID)) %>%
  mutate(state = map_chr(state_chr, ~ CapStr(.))) %>%
  select(state, geom)

tests_visual_data <- testing_by_state %>%
  left_join(us_tbl, by = c("province_state" = "state")) %>%
  select(province_state, confirmed, deaths, recovered, active, fips, people_tested, people_hospitalized, hospitalization_rate, geom)

# Plotting a visualization of cases as of April 1st in the US.

tests_visual_data %>%
  ggplot(aes(geometry = geom, fill = people_tested)) +
  geom_sf() +
  scale_fill_viridis_c(option = "plasma",
                       direction = -1) +
  labs(title = "Covid-19 Tests by State",
       caption = "Source: Johns Hopkins CSSE",
       fill = "Total Tests") +
  theme_void()


```

### NYTimes Data
```{r}

us_counties %>%
  filter(state == "New York")

counties <- st_as_sf(map("county", plot = FALSE, fill = TRUE)) %>%
  mutate(ID = as.character(ID)) %>%
  separate(ID, into = c("state", "county"), sep = ",") %>%
  mutate(state = map_chr(state, ~ CapStr(.)),
         county = map_chr(county, ~ CapStr(.)))

nystate_visual <- us_counties %>%
  filter(state == "New York", date == "2020-04-18") %>%
  left_join(counties, by = c("state", "county"))

nystate_visual %>%
  ggplot(aes(geometry = geom, fill = cases)) +
  geom_sf() +
  scale_fill_viridis_c(option = "plasma",
                       direction = -1) +
  labs(title = "Covid-19 Cases across New York State",
       caption = "Source: NYTimes",
       fill = "Total Tests") +
  theme_void()

```

### Modeling

```{r}

worldometer_regression <- lm(total_cases ~ total_tests, data = world) %>%
  tidy(conf.int = TRUE) %>%
  select(term, estimate, conf.low, conf.high)


worldometer_reps <- world %>%
  filter(! is.na(total_tests)) %>%
  select(country_other, incidence, total_cases, total_tests) %>%
  rep_sample_n(size = nrow(world), replace = TRUE, reps = 1000) %>%
  group_by(replicate) %>%
  nest() %>%
  mutate(mod = map(data, ~ lm(total_cases ~ total_tests, data = .)),
         reg_results = map(mod, ~ tidy(., conf.int = TRUE)),
         disp_coef = map_dbl(reg_results, ~ filter(., term == "total_tests") %>% pull(estimate)),
         lower_bound = map_dbl(reg_results, ~ filter(., term == "total_tests") %>% pull(conf.low)),
         upper_bound = map_dbl(reg_results, ~ filter(., term == "total_tests") %>% pull(conf.high)))

world_int <- worldometer_reps %>%
  pull(disp_coef) %>%
  quantile(c(0.025, 0.5, 0.975))



worldometer_model <- world %>%
  filter(! is.na(total_tests)) %>%
  select(country_other, incidence, total_cases, total_tests) %>%
  rep_sample_n(size = nrow(world), replace = TRUE, reps = 1000) %>%
  group_by(replicate, incidence) %>%
  nest() %>%
  mutate(mod = map(data, ~ lm(total_cases ~ total_tests, data = .)),
         reg_results = map(mod, ~ tidy(., conf.int = TRUE)),
         disp_coef = map_dbl(reg_results, ~ filter(., term == "total_tests") %>% pull(estimate)))
         # lower_bound = map_dbl(reg_results, ~ filter(., term == "total_tests") %>% pull(conf.low)),
         # upper_bound = map_dbl(reg_results, ~ filter(., term == "total_tests") %>% pull(conf.high)))

world_high <- worldometer_model %>%
  select(replicate, incidence, disp_coef) %>%
  filter(incidence == "100,000+ Cases") %>%
  pull(disp_coef) %>%
  quantile(c(0.025, 0.5, 0.975))

world_med <- worldometer_model %>%
  select(replicate, incidence, disp_coef) %>%
  filter(incidence == "10,000+ Cases") %>%
  pull(disp_coef) %>%
  quantile(c(0.025, 0.5, 0.975))

world_low <- worldometer_model %>%
  select(replicate, incidence, disp_coef) %>%
  filter(incidence == "1,000+ Cases") %>%
  pull(disp_coef) %>%
  quantile(c(0.025, 0.5, 0.975))

world_bottom <- worldometer_model %>%
  select(replicate, incidence, disp_coef) %>%
  filter(incidence == "Less than 1000+ Cases") %>%
  pull(disp_coef) %>%
  quantile(c(0.025, 0.5, 0.975))
 
updated_world_tibble <- tibble(index = "100,000+ Cases", conf_low = world_high[1], point_estimate = world_high[2], conf_high = world_high[3]) %>%
  add_row(index = "10,000+ Cases", conf_low = world_med[1], point_estimate = world_med[2], conf_high = world_med[3]) %>%
  add_row(index = "1,000+ Cases", conf_low = world_low[1], point_estimate = world_low[2], conf_high = world_low[3]) %>%
  add_row(index = "Less than 1,000 Cases", conf_low = world_bottom[1], point_estimate = world_bottom[2], conf_high = world_bottom[3])


ggplot(updated_world_tibble, aes(y = point_estimate)) +
  geom_errorbar(aes(x = index, ymin = conf_low, ymax = conf_high), width = 0.1, color = "#0D47A1") +
  theme_classic() +
  ylim(-0.05, .2) %>%
  labs(
    title = "Correlation between Total Tests and Total Cases",
    subtitle = "Modeled by running a linear regression \ncomparing case and test rates 1000 times",
    x = "Cases by Country",
    y = "Correlation"
  )



```





